site_name: OVD Contest 2023
site_author: David Leon (Dawei Leng)
docs_dir: docs

markdown_extensions:
    - pymdownx.arithmatex

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
    - Home: index.md
    - Data: data.md
    - News: news.md
    - Discussions: discussion.md
    - History: history.md

theme: mkdocs    

plugins:
  - git-revision-date-localized:
