site_name: 开放世界目标检测竞赛2023
site_author: David Leon (Dawei Leng)
docs_dir: docs

markdown_extensions:
    - pymdownx.arithmatex

extra_javascript:
    - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML

nav:
    - 赛题介绍: index.md
    - 数据下载: data.md
    - Leaderboard: leaderboard.md
    

theme: 
   # name: bootstrap4
   name: mkdocs
   nav_style: dark
   custom_dir: docs/resources/
   analytics:
     gtag: G-362080214


plugins:
  - git-revision-date-localized:
  - search:
      separator: '[\s\-\.]+'
